# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7f98ea8f89fb2490f6ce293cd0b48ebed39c64e35e0f356b25a3daf88156f6d67fe9797ecea13dc6dbb6b76a0abefd554bba78e4cebc369bf23c705497b001c

test:
  secret_key_base: 4fdcb997d81516c5c78d7821561a643656dcae86563f66ff64f4bb806268a2730bdef6dacc2b11e72c8258ae5f38c6154f08ca6991cd9a486d752a2f890b532c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
